---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p4-data
  namespace: helix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
...
