---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helix-p4d
  name: helix-p4d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helix-p4d
  template:
    metadata:
      labels:
        app: helix-p4d
    spec:
      volumes:
      - name: p4-storage
        persistentVolumeClaim:
          claimName: p4-data-pvc
      - name: p4-secrets
        secret:
          secretName: loginhook
      containers:
      - name: helix-p4d-basic
        image: 192.168.1.2:32000/helix-p4d-basic
        imagePullPolicy: Always
        ports:
        - containerPort: 1666
        volumeMounts:
        - name: p4-storage
          mountPath: /p4
        - name: p4-secrets
          mountPath: /opt/perforce/certs
          readOnly: true
...
