---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p4-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
...
